# ----
# Site

title: paljordawa
url: "paljordawa.github.io"
baseurl:
google_analytics_key: UA-104773879-1
disqus_shortname:
newsletter_action:
# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Knowledge base template for Jekyll.
author: 
  name: 
  email: paljordawa@gmail.com
  twitter: PaljorDawa
  instagram: PaljorDawa
social:
  name: Base Template
  links:
    - https://github.com/paljordawa/paljordawa.github.io

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - tzinfo

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
